service: theLuthers

useDotenv: true

frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-offline
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_REGION: ${env:COGNITO_REGION}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
